# src/test/modules/gpdb/test_logging/Makefile

subdir = src/test/modules/gpdb/test_logging
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk

check:
	$(prove_check)
